Fetch api
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #28
Opened 2020-12-31 17:19 UTC by KrolMateusz

Brakuje preprocessingu dla Vehicles oraz Starships

2021-01-02 16:44 UTC, htk4 requested changes
Moim zdaniem byłoby lepiej gdyby, przenieść pliki związane z SWAPI do folderu `app/infrastructure/`, natomiast `app/components/question.js` do `app/domain/question.js`.

2021-01-02 16:44 UTC, htk4 commented on src/app/components/fetchApi.js
> +
Co powiesz na wykorzystanie takiej funkcji:
```js
const fetchAllAndMapToJson = async (urls) => Promise.all(urls.map((url) => fetch(url).then((resp) => resp.json())));
```
wtedy:
```js
static async getPeopleJsonData() {
    return fetchAllAndMapToJson(peopleEndpoints);
}
```

2021-01-02 17:26 UTC, KrolMateusz commented on src/app/components/fetchApi.js
> +
Wprowadziłem zmiany, które zaproponowałeś. Skróciłem zapis w funkcji, bez tworzenia funkcji pomocniczej

2021-01-02 20:43 UTC, htk4 requested changes

2021-01-02 20:43 UTC, htk4 commented on test/processData.spec.js
> +            return PrepareData.preprocessData(peopleData).then((data) => {
Trochę te testy są bez sensu, bo nie sprawdzasz czy `PrepareData.preprocessData` poprawnie przetworzył `peopleData.json` w obiekty classy `Question` z odpowiednimi wartościami. Można by łatwo oszukać te testy implementując `PrepareData.preprocessData` na przykład tak:
```js
preprocessData(peopleData) {
 return Array(peopleData.length);
}
```
Co powiesz na takie rozwiązanie:
```js
import { Question } from '../src/app/domain/question';
import { PrepareData } from '../src/app/infrastructure/processData';

describe('Fetching data from API', () => {
    describe('check if people data', () => {
        test('process correctly', () => {
            const samplePerson1 = {
                name: 'Luke Skywalker',
                url: 'http://swapi.dev/api/people/1/',
            };
            const samplePerson2 = {
                name: 'C-3PO',
                url: 'http://swapi.dev/api/people/2/',
            };
            const samplePerson3 = {
                name: 'Chewbacca',
                url: 'http://swapi.dev/api/people/14/',
            };
            const sampleResults1 = {
                results: [samplePerson1, samplePerson2],
            };
            const sampleResults2 = {
                results: [samplePerson3],
            };
            const samplePeopleData = [sampleResults1, sampleResults2];
            const expected = [
                new Question('Luke Skywalker', 1),
                new Question('C-3PO', 2),
                new Question('Chewbacca', 14),
            ];

            const result = PrepareData.preprocessData(samplePeopleData);
            expect(result).toStrictEqual(expected);
        });
    });
});
```

2021-01-02 20:43 UTC, htk4 commented on src/app/infrastructure/processData.js
> +    static async preprocessData(jsonData) {
`async` nie jest tutaj potrzebne, ponieważ nigdzie nie wywołujesz `await` ani nie zwracasz `Promise`

2021-01-03 15:52 UTC, htk4 approved these changes

2021-01-03 15:57 UTC, htk4 commented
Jak będziesz mergował do maina wybierz opcję `Squash and merge` oraz dopisz w commit message:
```
FEATURE_ID: 4
TASK_ID: 14
```

2021-01-03 18:39 UTC, htk4 approved these changes

2021-01-03 18:58 UTC, dudeek approved these changes

2021-01-03 19:10 UTC, merged