Show answer states
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #29
Opened 2021-01-01 17:45 UTC by Haivex

Added states for buttons: hovered, correct, wrong

2021-01-02 16:24 UTC, htk4 requested changes

2021-01-02 16:24 UTC, htk4 commented on src/app/AnswerButton.js
> +export const generateAnswerButton = (button, isCorrectAnswer) => {
Wydaje mi się, że byłoby lepiej gdyby `generateAnswerButton` tworzył nowy button zamiast modyfikować button dany jako parametr funkcji. Po za tym jak dobrze określiłeś `AnswerButton` ma kilka stanów: ['selected', 'correct', 'wrong', hovered'], więc fajnie byłoby dać możliwość osobie która będzie z niego korzystać aby mogła zmieniać jego stan (przy okazji wygląd). Przykładowe rozwiązanie:
```js
const generateAnswerButton = ({ text, onClick }) => {
    const state = { isSelectedAnswer: false, text: text };
    const button = document.createElement('button');
    button.classList.add('answer');
    button.appendChild(document.createTextNode(text));
    const view = {
        element: button,
        select: () => { ... },
        unselect: () => { ... },
        markAsCorrect: () => { ... },
        markAsWrong: () => { ... },
        isSelectedAnswer: () => state.isSelectedAnswer,
        text: () => state.text,
    };
    // setup listeners, etc.
    return view;
```

2021-01-02 16:24 UTC, htk4 commented on src/styles/AnswerButton.scss
> +.answer {
Aby dołączyć style musisz w pliku `AnswerButton.scss` dodać `import '../styles/AnswerButton.scss';`. Nazwy które nadałeś są dość ogólne, a ponieważ jeszcze nie skonfigurowaliśmy css modules (i nie wiem czy skonfigurujemy :P), to dobrze byłoby używać jakiegoś prefixu np. `answer-button-` wtedy `hovered` zamieni się na `answer-button-hovered`.

2021-01-06 17:06 UTC, KrolMateusz approved these changes

2021-01-07 21:37 UTC, htk4 approved these changes

2021-01-08 11:46 UTC, merged