Questions set
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #31
Opened 2021-01-02 18:19 UTC by bat098

2021-01-02 21:46 UTC, htk4 requested changes

2021-01-02 21:46 UTC, htk4 commented on src/app/infrastructure/RandData.js
> +        const categoryArr = await PrepareData.preprocessData(peopleData); //Tablica wszystkich obiektów z danej kategori
`categoryArr` powinna być przyjmowana jako parametr do funkcji albo w konstruktorze klasy. W tym momencie uzależniasz `randData` od `Data.getPeopleJsonData` oraz `PrepareData.preprocessData`, przez co funkcja `randData` nie może być użyta np. do vehicles.

2021-01-02 21:46 UTC, htk4 commented on src/app/infrastructure/RandData.js
> +        const randElementsfromArr = (count, arr) => {
Twoja implementacja nie gwarantuje zakończenia pętli `while`. Efektywniej byłoby wykorzystać algorytm [Fisher-Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Fisher_and_Yates'_original_method) dostępny np. w bibliotece [lodash](https://lodash.com/docs/4.17.15#shuffle) i później pobrać n pierwszych elementów za pomocą funkcji [_.take](https://lodash.com/docs/4.17.15#take).

2021-01-02 21:46 UTC, htk4 commented on src/app/infrastructure/RandData.js
> +            answer.sort((a,b) => parseInt(a.index) - parseInt(b.index)) // wymieszanie odpowiedzi (poprawna odpowiedz nie jest już zawsze pierwsza)
Lepiej użyć [_.shuffle](https://lodash.com/docs/4.17.15#shuffle)

2021-01-04 20:12 UTC, htk4 requested changes

2021-01-04 20:12 UTC, htk4 commented on src/app/infrastructure/RandData.js
> +                categoryArr = await data.getPeopleJsonData().then(res => prepareData.preprocessData(res) )
W przypadku podania złej kategorii powinniśmy rzucać wyjątek, ponieważ w tym przypadku oznacza to, że mamy błąd w kodzie i łatwiej będzie go znaleźć kiedy rzucimy `Error`, niż gdy wykona się z losową wartością (wtedy dużo trudniej jest zidentyfikować gdzie jest problem) .

2021-01-05 19:08 UTC, htk4 approved these changes

2021-01-05 20:52 UTC, KrolMateusz approved these changes

2021-01-05 21:28 UTC, merged