Choose question
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #32
Opened 2021-01-02 20:32 UTC by bat098

2021-01-02 22:13 UTC, htk4 requested changes

2021-01-02 22:13 UTC, htk4 commented on src/app/infrastructure/chooseQuestion.js
> +    const inputData = await RandData.randData()
`inputData` powinien być parametrem funkcji. Nie jest potrzebne, aby za każdym razem wywołując `chooseQuestions` od nowa losować pytania. A najlepiej by było, gdyby `randData` zwracał `Array` wtedy łatwo można wybrać pytanie za pomocą indeksu `inputData[0]` i nie potrzebna jest funkcja `chooseQuestions` .

2021-01-02 22:13 UTC, htk4 commented on src/app/infrastructure/chooseQuestion.js
> +    const question = {
To co zwraca funkcja lepiej zamknąć w klasie i tą klasę dodać do folderu `/app/domain/`.

2021-01-05 21:35 UTC, bat098 commented
Nie ma sensu tworzenia komponentu wyświetlającego jedno pytanie #HubertPewneInfo

2021-01-05 21:35 UTC, closed without merging