UI | Style
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #34
Opened 2021-01-03 13:43 UTC by Ania-Em

Ref Feature #7

2021-01-03 16:43 UTC, htk4 requested changes

2021-01-03 16:43 UTC, htk4 commented on src/styles/_common.scss
> +@use '../../../styles/colors';
Powinno być `@use './colors';`

2021-01-03 18:57 UTC, htk4 approved these changes

2021-01-04 20:35 UTC, bat098 approved these changes

2021-01-04 23:00 UTC, merged