Death star times
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #37
Opened 2021-01-03 23:02 UTC by dudeek

Problem z animacją gwiazdy śmierci.

2021-01-05 08:17 UTC, KrolMateusz requested changes

2021-01-05 08:17 UTC, KrolMateusz commented on src/app/components/deathStar.js
> +    document.body.appendChild(deathStarDiv);
Nie powinieneś dodawać elementu to `body`. Dodawaniem komponentów będzie zajmować się oddzielna funkcja.

2021-01-05 08:17 UTC, KrolMateusz commented on src/app/components/deathStar.js
> +    return deathStarDiv();
`deathStarDiv` nie jest funkcją, więc nawiasy są zbędne. Funkcja powinna zwracać po prostu
```js
return deathStarDiv;
```

2021-01-05 19:12 UTC, htk4 requested changes
Dodaj `.DS_Store` do `.gitignore` żeby nie dodawać niepotrzebnych plików

2021-01-06 18:35 UTC, KrolMateusz approved these changes

2021-01-07 22:40 UTC, htk4 approved these changes

2021-01-07 22:41 UTC, merged