Computer score UI
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #76
Opened 2021-01-13 13:16 UTC by bat098

2021-01-13 18:40 UTC, Haivex approved these changes

2021-01-13 22:07 UTC, KrolMateusz requested changes

2021-01-13 22:07 UTC, KrolMateusz commented on src/app/components/ComputerScore.js
> +        getData();
Niepotrzebne zapytanie do API, które spowalnia działanie aplikacji. Nadrzędny komponent ma informacje na temat osób (o ile wybierzemy kategorię people), więc moim zdaniem powinieneś jako parametr przyjmować listę obiektów (tak jak w `randData.js`). Następnie możesz zrobić skorzystać z `Array.protorype.map()', żeby pobrać potrzebne imiona dla komputera. Np.
```js
const data = [{ name: 'Luke Skywalker', index: 1 }, { name: 'Jar Jar Binks', index: 2 }];
const names = data.map((person) => person.name);
```

2021-01-16 16:03 UTC, KrolMateusz approved these changes

2021-01-16 16:03 UTC, merged