UI component | Menu główne | Przyciski zasady, ranking, rozpocznij grę
CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #81
Opened 2021-01-13 22:00 UTC by KrolMateusz

2021-01-14 14:49 UTC, bat098 commented on src/app/components/Rules.js
> +    const rulesText = `You have one minute (1m) to answer 10 questions. During the game on each question you need to select who or what from Star Wars is showed on the left from available options.`;
Zasady powinny być umieszczone w oddzielnym pliku. Gdyby zasady zajmowały np. 2 strony A4 wrzucenie ich do kodu tego komponent nie byłoby najlepszym rozwiązaniem ze względu na czytelność.

2021-01-14 19:14 UTC, bat098 approved these changes

2021-01-15 13:28 UTC, Haivex requested changes
Ciekawy pomysł z tym modalem że jest taki element w HTMLu jak dialog :)

2021-01-15 13:28 UTC, Haivex approved these changes

2021-01-15 14:54 UTC, merged